### ISSUE TITLE
[Egg Request]: Vaultwarden

### ISSUE THREAD

**Issue by Lovinoes** [pelican-eggs/eggs#2936]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/dani-garcia/vaultwarden

### Links for the download

Docker: https://hub.docker.com/r/vaultwarden/server
Github: https://github.com/dani-garcia/vaultwarden/releases/latest

### Links for the install docs

https://github.com/dani-garcia/vaultwarden#installation

**Comment by Lovinoes** [comment]
Docker Compose file can be found at https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose

**Comment by gOOvER** [comment]
> Docker Compose file can be found at https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose

not possible, because it needs a webserver

```
 caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
```
